# action.yml
name: 'Curly-action'
description: 'Calls a rest api and returns output to the next step'
inputs:
  api:  # id of input
    description: 'api to call'
    required: true
    default: 'https://dummyapi.io/data/api/user?limit=10'
outputs:
  response:
    description: 'Json response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api }}
