# action.yml
name: 'Curly'
description: 'Url to curl'
inputs:
  url:  # id of input
    description: 'url'
    required: true
    default: 'https://www.google.com'
outputs:
  response: # id of output
    description: 'Json response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}