# action.yml
name: 'Curly'
description: 'Calling a rest api and out Json'
inputs:
  api:  # id of input
    description: 'api to call'
    required: true
    default: 'https://www.google.com'
outputs:
  response: # id of output
    description: 'Json response'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.api }}