on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Curling Json
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Json
        uses: ./ # Uses an action in the root directory
        id: curl
        with:
          url: 'https://reqbin.com/echo/get/json'
      # Use the output from the `hello` step
      - name: Output Json
        run: echo "JsonResponse= ${{ steps.curl.outputs.response }}"