on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Call rest api and Print response
    steps:
      - name: Call Api
        uses: ikru92/curly-action@main
        id: curl
        with:
          api: 'https://dummyapi.io/data/api/user?limit=5'
      - name: Print response
        run: echo "JsonResponse= ${{ steps.curl.outputs.response }}"
